type Props = { roomId: string };

export default function OverviewTab({ roomId }: Props) {
  return (
    <div className="space-y-4">
      reports will be generated by ai agent <br></br> {roomId}
    </div>
  );
}
